name: forex
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - notebook
  - pandas
  - matplotlib
  - requests
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - sortedcontainers
  - apscheduler
  - sqlalchemy
  - munch
  - pyyaml
  - pip:
    - oandapyV20