# Settings file for training a model
model:
  # Model configuration. Should refer to a config file and pretrained model file
  config_file:  'model.yaml' # Config file name inside configs/models/. '.yaml' is optional TODO!
  pt_path:      'markov2n_8_M1_%i.pt' # Pretrained file path. '.pt' is optional, but this argument is not. 
  #If %i is in the string, it will be replaced by an index for the trained model

retrieval:
  # Retrieval settings for retrieving the model input
  soft_margin:  0.2     # Or should we include this in the model config?
  soft_gran:    'D'     # Include to use a standard granularity. Will be multiplied with soft_margin
  
time_series:
  # Settings for the complete cache of candlesticks to draw sequences from
  start_time:   '2016-01-01'
  granularity:  'D'     # Retrieval granularity, should be quite small. 
  # Can be number of seconds, or granularity string
  skip_wknd:    True

dataset:
  # Settings for data loading during training
  random_split: True # Split data at random into train/val/test sets or now
  shuffle:      True # Shuffle data during training
  val_split:    0.4
  test_split:   0.1

epochs:         2 # Max. number of epochs to train for
min_epochs:     1 # Minimum number of epochs before early stopping is allowed
model_notes:    "Test model"
